version: '3.8'
services:

  tidb-br:
    image: abhishek26102001/br:latest
    command: /bin/bash -c "sleep infinity"
    restart: always

  pd:
    image: pingcap/pd:v8.5.0
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - ./config/pd-nightly-tiflash.toml:/pd.toml
      - pd_data:/data
      - ./certs:/certs
    command:
      - --name=pd
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd:2379
      - --advertise-peer-urls=http://pd:2380
      - --initial-cluster=pd=http://pd:2380,pd1=http://pd1:2380,pd2=http://pd2:2380
      - --data-dir=/data
      - --config=/pd.toml

    restart: always

  pd1:
    image: pingcap/pd:v8.5.0
    volumes:
      - ./config/pd-nightly-tiflash.toml:/pd.toml
      - pd1_data:/data
      - ./certs:/certs
    command:
      - --name=pd1
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd1:2379
      - --advertise-peer-urls=http://pd1:2380
      - --initial-cluster=pd=http://pd:2380,pd1=http://pd1:2380,pd2=http://pd2:2380
      - --data-dir=/data
      - --config=/pd.toml

    restart: always

  pd2:
    image: pingcap/pd:v8.5.0
    volumes:
      - ./config/pd-nightly-tiflash.toml:/pd.toml
      - pd2_data:/data
      - ./certs:/certs
    command:
      - --name=pd2
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd2:2379
      - --advertise-peer-urls=http://pd2:2380
      - --initial-cluster=pd=http://pd:2380,pd1=http://pd1:2380,pd2=http://pd2:2380
      - --data-dir=/data
      - --config=/pd.toml

    restart: always

  tikv:
    image: pingcap/tikv:v8.5.0
    ports:
      - "20160:20160"
    volumes:
      - tikv_data:/data
      - ./certs:/certs
      - ./config/tikv.toml:/tikv.toml:ro
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv:20160
      - --status-addr=0.0.0.0:20180
      - --pd=pd:2379,pd1:2379,pd2:2379
      - --data-dir=/data
      - --config=/tikv.toml
    depends_on:
      - pd
    restart: always


  tikv1:
    image: pingcap/tikv:v8.5.0
    volumes:
      - tikv1_data:/data
      - ./certs:/certs
      - ./config/tikv.toml:/tikv.toml:ro
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv1:20160
      - --status-addr=0.0.0.0:20180
      - --pd=pd1:2379,pd:2379,pd2:2379
      - --data-dir=/data
      - --config=/tikv.toml
    depends_on:
      - pd1
    restart: always

  tikv2:
    image: pingcap/tikv:v8.5.0
    volumes:
      - tikv2_data:/data
      - ./certs:/certs
      - ./config/tikv.toml:/tikv.toml:ro
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv2:20160
      - --status-addr=0.0.0.0:20180
      - --pd=pd2:2379,pd:2379,pd1:2379
      - --data-dir=/data
      - --config=/tikv.toml
  
    depends_on:
      - pd2
    restart: always
  tidb:
    image: pingcap/tidb:v8.5.0
    ports:
      - "4000:4000"
      - "10080:10080"
    command:
      - --status=10080
      - --store=tikv
      - --path=pd:2379,pd1:2379,pd2:2379
      - --advertise-address=tidb
      - --metrics-addr=pushgateway:9091
      - --config=/tidb.toml
    volumes:
      - ./certs:/certs
      - ./config/tidb.toml:/tidb.toml:ro
    depends_on:
      - tikv
      - tikv1
      - tikv2
    restart: always

  tidb1:
    image: pingcap/tidb:v8.5.0
    command:
      - --status=10080
      - --store=tikv
      - --path=pd:2379,pd1:2379,pd2:2379
      - --advertise-address=tidb1
      - --metrics-addr=pushgateway:9091
      - --config=/tidb.toml
    volumes:
      - ./certs:/certs
      - ./config/tidb.toml:/tidb.toml:ro
    depends_on:
      - tikv
      - tikv1
      - tikv2
    restart: always
    
  tidb2:
    image: pingcap/tidb:v8.5.0
    command:
      - --status=10080
      - --store=tikv
      - --path=pd:2379,pd1:2379,pd2:2379
      - --advertise-address=tidb2
      - --metrics-addr=pushgateway:9091
      - --config=/tidb.toml
    volumes:
      - ./certs:/certs
      - ./config/tidb.toml:/tidb.toml:ro
    depends_on:
      - tikv
      - tikv1
      - tikv2
    restart: always
    


  tiflash:
    image: pingcap/tiflash:v8.5.0
    ports:
      - "3930:3930"   # TiFlash service port
      - "20170:20170" # TiFlash proxy port
      - "20181:20181" # TiFlash proxy status port
      - "9000:9000"   # MPP port
      - "8123:8123"   # HTTP port

    cap_add:
      - SYS_NICE
    volumes:
      - ./config/tiflash-nightly.toml:/tiflash.toml:ro
      - ./config/tiflash-learner-nightly.toml:/proxy.toml:ro
      - ./tiflash_data:/data 
      - ./logs:/logs
      - ./certs:/certs
    command:
      - --config=/tiflash.toml  
 

  tiproxy:
    image: abhishek26102001/tiproxy:v1
    ports:
      - "6000:6000"
      - "3080:3080"

    volumes:
      - ./config/proxy.toml:/proxy.toml:ro
      - ./certs:/certs
    command:
      - --config=/proxy.toml

      
    depends_on:
      - tidb
      - tidb1
      - tidb2
    restart: always


  ngmonitoring:
    image: pingcap/ng-monitoring:v8.5.0
    ports:
      - "12020:12020"   
    volumes:
      - ./config/ng-monitor.toml:/ng-monitor.toml:ro
      - ./data:/data
    command:
      - --config=/ng-monitor.toml  

    depends_on:
      - tikv
      - tidb
    restart: always

  pushgateway:
    image: prom/pushgateway:latest
    command:
      - --log.level=error
    restart: on-failure
  prometheus:
    user: root
    image: prom/prometheus:latest
    command:
      - --log.level=error
      - --storage.tsdb.path=/data/prometheus
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/pd.rules.yml:/etc/prometheus/pd.rules.yml:ro
      - ./config/tikv.rules.yml:/etc/prometheus/tikv.rules.yml:ro
      - ./config/tidb.rules.yml:/etc/prometheus/tidb.rules.yml:ro
      - ./data:/data
    restart: on-failure
  grafana:
    image: grafana/grafana:6.0.1
    user: "0"
    environment:
      GF_LOG_LEVEL: error
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
    volumes:
      - ./config/grafana:/etc/grafana
      - ./config/dashboards:/tmp/dashboards
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: on-failure

volumes:
  pd_data:
  pd1_data:
  pd2_data:
  tikv_data:
  tikv1_data:
  tikv2_data:
  tiflash_data:
