advertise-addr = "tiproxy:6000"
[proxy]
addr = "0.0.0.0:6000"
max-connections = 0
pd-addrs = "pd:2379,pd1:2379,pd2:2379"

[api]
addr = "0.0.0.0:3080"


[security]
    [sql-tls]
    skip-ca = true
    [server-tls]
    auto-certs = true


[metric]
# the Prometheus client push interval. Setting the value to 0s stops Prometheus client from pushing.
interval = "15s"
# the Prometheus pushgateway address. Leaving it empty stops Prometheus client from pushing.
address = "pushgateway:9091"
# the Prometheus client push job name. Note: A node id will automatically append, e.g., "tikv_1".
job = "tiproxy"