default_profile = "default"
display_name = "TiFlash"
listen_host = "0.0.0.0"
mark_cache_size = 5368709120
tmp_path = "/data/tmp"
path = "/data"
tcp_port = 9110
http_port = 8223

[flash]
tidb_status_addr = "tidb:10080,tidb1:10080,tidb2:10080"
service_addr = "tiflash:3930"

[flash.flash_cluster]
cluster_manager_path = "/tiflash/flash_cluster_manager"
log = "/logs/tiflash_cluster_manager.log"
master_ttl = 60
refresh_interval = 20
update_rule_interval = 5

[flash.proxy]
addr = "0.0.0.0:20170"
advertise-addr = "tiflash:20170"
advertise-status-addr = "tiflash:20181"
status-addr = "0.0.0.0:20181"
config = "/proxy.toml"


[status]
metrics_port = 8234


[application]
runAsDaemon = true

[raft]
pd_addr = "pd:2379,pd1:2379,pd2:2379"
storage_engine = "tmt"

[quotas]

[quotas.default]

[quotas.default.interval]
duration = 3600
errors = 0
execution_time = 0
queries = 0
read_rows = 0
result_rows = 0

[users]

[users.default]
password = ""
profile = "default"
quota = "default"

[users.default.networks]
ip = "::/0"

[users.readonly]
password = ""
profile = "readonly"
quota = "default"

[users.readonly.networks]
ip = "::/0"



[metric]
# the Prometheus client push interval. Setting the value to 0s stops Prometheus client from pushing.
interval = "15s"
# the Prometheus pushgateway address. Leaving it empty stops Prometheus client from pushing.
address = "pushgateway:9091"
# the Prometheus client push job name. Note: A node id will automatically append, e.g., "tikv_1".
job = "tiflash"

