
[readpool]

[readpool.coprocessor]

[readpool.storage]


[storage]
data-dir = "/data/flash"

[pd]

[metric]

[raftstore]
capacity = "10GB"

[coprocessor]

[rocksdb]
wal-dir = ""

[rocksdb.defaultcf]

[rocksdb.lockcf]

[rocksdb.writecf]

[raftdb]

[raftdb.defaultcf]

[security]
ca-path = ""
cert-path = ""
key-path = ""

[import]
