path = "/tmp/tiflash/data"
capacity = "10737418240"

tcp_port = 9000

[flash]
service_addr = "0.0.0.0:3930"
[flash.proxy]
addr = "127.0.0.1:20180"
advertise-addr = "tiflash:20170"
data-dir = "/tmp/tiflash/proxy"
config = "/proxy.toml"
log-file = "/tmp/tiflash/log/tiflash_tikv.log"
engine-addr = "tiflash:3930"
status-addr = "0.0.0.0:20181"
advertise-status-addr = "tiflash:20181"

[logger]
count = 10
log = "/tmp/tiflash/log/tiflash.log"
errorlog = "/tmp/tiflash/log/tiflash_error.log"
size = "1000M"
level = "trace"

[raft]
pd_addr = "pd:2379"

[profiles]
[profiles.default]
# max_memory_usage = 0